language: rust
dist: xenial

cache:
  - directories:
    - $HOME/.cargo
    - target/debug/deps
    - target/$TARGET/debug/deps
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

addons:
  apt:
    packages:
      - fakeroot
      - musl-dev
      - musl-tools

env:
  global:
    - PROJECT_NAME=cargo-watch

matrix:
  include:
    # Default test+release versions
    - os: windows
      rust: stable
      env: TARGET=x86_64-pc-windows-msvc
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

    # Extra targets, also released
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl

    # Rust minimum version (check only)
    - os: linux
      rust: 1.38.0
      env: TARGET=x86_64-unknown-linux-gnu

    # Non-critical, best-effort
    - os: windows
      rust: stable
      env: TARGET=x86_64-pc-windows-gnu

  allow_failures:
    - rust: nightly
    - env: TARGET=x86_64-pc-windows-gnu
  fast_finish: true

before_script:
  - rustup target add $TARGET || true
  - rustup component add --target $TARGET rustfmt || true
  - rm tests/touchdata/*.txt || true
script:
  - cargo check --target $TARGET
  - |
    if [[ $TRAVIS_RUST_VERSION != "1.26.1" ]] && [[ $TRAVIS_OS_NAME == "linux" ]]; then
      cargo install --debug --path .
      cargo test --target $TARGET
    fi

before_deploy: ./.package $TRAVIS_TAG $TARGET
deploy:
  provider: releases
  api_key:
    secure: LXi48d/kJVntJKV0SjKk9HHMc3IzxQt+3YY2PDDB7toQmVOf6mVdaRHSLQ5p08g6R4/z2hzsqDaKC7lvy1E5BuQotMJ9b4uw5ZiAE534CHr2IgQIwTJvV4gweC9fwZk8Ln8k3PY0Z9wLy/tzWaZHo9WK4IqjB4XrTOhR2vDoaq0=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  skip_cleanup: true
  on:
    repo: passcod/cargo-watch
    tags: true
    rust: stable
